steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/helloworld:latest', '.' ]

# images: [gcr.io/$PROJECT_ID/helloworld:latest]
options:
  logging: CLOUD_LOGGING_ONLY